// NotesMaker.js
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { onAuthStateChanged } from "firebase/auth";
import { doc, setDoc } from "firebase/firestore";
import { db, auth } from "../../firebase/firebase";
import {
  Container,
  Row,
  Col,
  Button,
  Form,
  Alert,
  Spinner,
  Card,
  Modal,
} from 'react-bootstrap';

const NotesMaker = () => {
  // State Variables
  const [inputText, setInputText] = useState("");
  const [suggestions, setSuggestions] = useState([]);
  const [customSuggestions, setCustomSuggestions] = useState([]);
  const [customInput, setCustomInput] = useState("");
  const [selectedSuggestions, setSelectedSuggestions] = useState(new Set());
  const [confirmed, setConfirmed] = useState(false);
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [hasGeneratedPrompt, setHasGeneratedPrompt] = useState(false);
  const [showPromptModal, setShowPromptModal] = useState(false);
  const [hasCopiedPrompt, setHasCopiedPrompt] = useState(false);
  const [pastedOutput, setPastedOutput] = useState('');
  const [isOutputConfirmed, setIsOutputConfirmed] = useState(false);
  const [user, setUser] = useState(null);
  const [alert, setAlert] = useState({ show: false, variant: '', message: '' });
  const [noteTitle, setNoteTitle] = useState("");
  const [showSaveDisclaimer, setShowSaveDisclaimer] = useState(false);

  const navigate = useNavigate();

  // Authentication State
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
      if (!currentUser) {
        setAlert({
          show: true,
          variant: 'warning',
          message: 'You must be signed in to use the NotesMaker.',
        });
      }
    });
    return () => unsubscribe();
  }, []);

  // Handler to confirm input and suggestions
  const handleConfirm = () => {
    if (!inputText.trim()) {
      setAlert({ show: true, variant: 'danger', message: 'Please enter some text.' });
      return;
    }

    if (selectedSuggestions.size === 0) {
      setAlert({ show: true, variant: 'danger', message: 'Please select or add at least one suggestion.' });
      return;
    }

    setConfirmed(true);
    setAlert({ show: true, variant: 'success', message: 'Input confirmed. You can now generate the prompt.' });
  };

  // Handler to generate prompt
  const handleGenerate = () => {
    if (!confirmed) {
      setAlert({ show: true, variant: 'warning', message: 'Please confirm your input first.' });
      return;
    }

    generatePrompt();
    setAlert({ show: true, variant: 'info', message: 'Prompt generated. You can copy it now.' });
    setHasGeneratedPrompt(true);
  };

  // Function to generate the structured prompt
  const generatePrompt = () => {
    const selectedSuggestionsArray = Array.from(selectedSuggestions).map(id => {
      const suggestion = suggestions.find(s => s.id === id) || customSuggestions.find(s => s.id === id);
      return suggestion ? suggestion.text : '';
    }).filter(text => text !== '');

    const suggestionsText = selectedSuggestionsArray.join(", ");

    const promptTemplate = `You are an expert note-taking assistant. Based on the following content and suggestions, create organized and comprehensive notes.

**Content:**
${inputText}

**Suggestions:**
${suggestionsText}

**Instructions:**
1. Structure the notes clearly with appropriate headings and subheadings.
2. Use bullet points where necessary for better readability.
3. Ensure the notes cover all key concepts and details from the content.
4. Maintain proper grammar and punctuation.
5. Avoid adding any personal opinions or additional information outside of the provided content and suggestions.`;

    setGeneratedPrompt(promptTemplate);
  };

  // Handler for confirming pasted output
  const handleConfirmOutput = async () => {
    if (!pastedOutput.trim()) {
      setAlert({ show: true, variant: 'danger', message: 'Please paste the output generated by ChatGPT.' });
      return;
    }

    if (!noteTitle.trim()) {
      setAlert({ show: true, variant: 'danger', message: 'Please provide a title for your notes.' });
      return;
    }

    setAlert({ show: false, variant: '', message: '' });

    try {
      setIsOutputConfirmed(true);
      await saveNotes(noteTitle, pastedOutput);
      setAlert({ show: true, variant: 'success', message: 'Notes saved successfully.' });
      navigate(`/notes/${encodeURIComponent(noteTitle)}`);
    } catch (error) {
      console.error('Error saving notes:', error);
      setAlert({ show: true, variant: 'danger', message: 'Failed to save notes. Please try again.' });
    }
  };

  // Function to save notes to Firestore
  const saveNotes = async (title, content) => {
    const noteDocRef = doc(db, `users/${user.uid}/notes`, title);
    await setDoc(
      noteDocRef,
      {
        title: title,
        content: content,
        createdAt: new Date(),
      },
      { merge: true }
    );
  };

  // Handlers for suggestions
  const toggleSuggestion = (id) => {
    setSelectedSuggestions((prev) => {
      const newSelected = new Set(prev);
      if (newSelected.has(id)) {
        newSelected.delete(id);
      } else {
        newSelected.add(id);
      }
      return newSelected;
    });
  };

  const addCustomSuggestion = () => {
    if (!customInput.trim()) {
      return;
    }

    const newSuggestion = {
      id: suggestions.length + customSuggestions.length + 1, // Ensure unique ID
      text: customInput.trim(),
    };

    const updatedCustomSuggestions = [...customSuggestions, newSuggestion];
    setCustomSuggestions(updatedCustomSuggestions);

    const updatedSelectedSuggestions = new Set(selectedSuggestions);
    updatedSelectedSuggestions.add(newSuggestion.id);
    setSelectedSuggestions(updatedSelectedSuggestions); // Activate the new suggestion

    setCustomInput(""); // Clear the input field
  };

  const removeCustomSuggestion = (id) => {
    setCustomSuggestions(
      customSuggestions.filter((suggestion) => suggestion.id !== id)
    );
    setSelectedSuggestions((prev) => {
      const newSelected = new Set(prev);
      newSelected.delete(id);
      return newSelected;
    });
  };

  // Handler to reset all fields
  const handleReset = () => {
    setInputText("");
    setSuggestions([]);
    setCustomSuggestions([]);
    setCustomInput("");
    setSelectedSuggestions(new Set());
    setGeneratedPrompt('');
    setHasGeneratedPrompt(false);
    setHasCopiedPrompt(false);
    setPastedOutput('');
    setIsOutputConfirmed(false);
    setNoteTitle("");
    setAlert({ show: false, variant: '', message: '' });
  };

  // Handler to save notes (after pasting output)
  const handleSaveClick = () => {
    setShowSaveDisclaimer(true);
  };

  const confirmSave = async () => {
    await handleConfirmOutput();
    setShowSaveDisclaimer(false);
  };

  return (
    <Container className="my-5">
      <h2 className="mb-4 text-center">NotesMaker</h2>

      {alert.show && (
        <Alert
          variant={alert.variant}
          onClose={() => setAlert({ ...alert, show: false })}
          dismissible
        >
          {alert.message}
        </Alert>
      )}

      {/* Step 1: Input Content and Suggestions */}
      {!hasGeneratedPrompt && !isOutputConfirmed && (
        <Card className="mb-4">
          <Card.Body>
            <Form.Group controlId="notesText" className="mb-3">
              <Form.Label>Enter Text for Notes</Form.Label>
              <Form.Control
                as="textarea"
                rows={6}
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Enter the large body of text here..."
                maxLength={1000}
              />
              <Form.Text className="text-muted">{inputText.length}/1000 characters</Form.Text>
            </Form.Group>

            <h5 className="mt-4">Add Suggestions</h5>
            <div className="d-flex flex-wrap">
              {suggestions.map((suggestion) => (
                <Card 
                  key={suggestion.id} 
                  className={`m-2 p-2 ${selectedSuggestions.has(suggestion.id) ? 'border-primary' : ''}`} 
                  style={{ cursor: 'pointer', width: '150px' }}
                  onClick={() => toggleSuggestion(suggestion.id)}
                >
                  <Card.Text>{suggestion.text}</Card.Text>
                </Card>
              ))}
              {customSuggestions.map((suggestion) => (
                <Card 
                  key={suggestion.id} 
                  className={`m-2 p-2 ${selectedSuggestions.has(suggestion.id) ? 'border-primary' : ''}`} 
                  style={{ cursor: 'pointer', width: '150px', position: 'relative' }}
                  onClick={() => toggleSuggestion(suggestion.id)}
                >
                  <Card.Text>{suggestion.text}</Card.Text>
                  <Button 
                    variant="danger" 
                    size="sm" 
                    style={{ position: 'absolute', top: '5px', right: '5px' }}
                    onClick={(e) => {
                      e.stopPropagation();
                      removeCustomSuggestion(suggestion.id);
                    }}
                  >
                    &times;
                  </Button>
                </Card>
              ))}
            </div>

            <Form.Group controlId="customSuggestion" className="mt-3">
              <Form.Control 
                type="text" 
                value={customInput} 
                onChange={(e) => setCustomInput(e.target.value)} 
                placeholder="Add your own suggestion" 
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    addCustomSuggestion();
                  }
                }}
              />
              <Button 
                variant="secondary" 
                className="mt-2" 
                onClick={addCustomSuggestion}
                disabled={!customInput.trim()}
              >
                Add Suggestion
              </Button>
            </Form.Group>

            <Button
              variant="primary"
              onClick={handleConfirm}
              disabled={isOutputConfirmed}
              className="w-100 mt-4"
            >
              {isOutputConfirmed ? 'Input Confirmed' : 'Confirm Input'}
            </Button>
          </Card.Body>
        </Card>
      )}

      {/* Step 2: Generate Prompt */}
      {confirmed && !hasGeneratedPrompt && !isOutputConfirmed && (
        <Button
          variant="success"
          onClick={handleGenerate}
          disabled={isOutputConfirmed}
          className="w-100 mb-3"
        >
          {isOutputConfirmed ? 'Prompt Generated' : 'Generate Prompt'}
        </Button>
      )}

      {/* Step 3: View/Edit and Copy Prompt */}
      {hasGeneratedPrompt && !hasCopiedPrompt && !isOutputConfirmed && (
        <>
          <Alert variant="info">Prompt generated. You can copy it now.</Alert>
          <Button
            variant="secondary"
            onClick={() => setShowPromptModal(true)}
            className="w-100 mb-2"
          >
            View/Edit Prompt
          </Button>
          <Button
            variant="primary"
            onClick={() => {
              navigator.clipboard.writeText(generatedPrompt);
              setAlert({ show: true, variant: 'success', message: 'Prompt copied to clipboard.' });
              setHasCopiedPrompt(true);
            }}
            className="w-100"
          >
            Copy Prompt
          </Button>

          {/* Prompt Modal */}
          <Modal show={showPromptModal} onHide={() => setShowPromptModal(false)} centered size="lg">
            <Modal.Header closeButton>
              <Modal.Title>Generated Prompt</Modal.Title>
            </Modal.Header>
            <Modal.Body>
              <Alert variant="warning">Editing this prompt might cause unexpected results.</Alert>
              <Form.Control
                as="textarea"
                rows={15}
                value={generatedPrompt}
                onChange={(e) => setGeneratedPrompt(e.target.value)}
              />
            </Modal.Body>
            <Modal.Footer>
              <Button variant="secondary" onClick={() => setShowPromptModal(false)}>
                Close
              </Button>
            </Modal.Footer>
          </Modal>
        </>
      )}

      {/* Step 4: Paste Output */}
      {hasCopiedPrompt && !isOutputConfirmed && (
        <>
          <Form.Group controlId="pastedOutput" className="mb-3">
            <Form.Label>Paste ChatGPT Output Below</Form.Label>
            <Form.Control
              as="textarea"
              rows={15}
              value={pastedOutput}
              onChange={(e) => setPastedOutput(e.target.value)}
              placeholder="Paste the output generated by ChatGPT here..."
            />
          </Form.Group>
          <Button
            variant="success"
            onClick={handleSaveClick}
            disabled={isOutputConfirmed || !pastedOutput.trim()}
            className="w-100"
          >
            Save Notes
          </Button>
        </>
      )}
      <Modal show={showSaveDisclaimer} onHide={() => setShowSaveDisclaimer(false)}>
        <Modal.Header closeButton>
          <Modal.Title>Save Your Notes</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Form.Group controlId="noteTitle">
            <Form.Label>Please provide a title for your notes:</Form.Label>
            <Form.Control 
              type="text" 
              value={noteTitle} 
              onChange={(e) => setNoteTitle(e.target.value)} 
              placeholder="Enter title"
            />
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="primary" onClick={confirmSave}>
            Save
          </Button>
          <Button variant="secondary" onClick={() => setShowSaveDisclaimer(false)}>
            Cancel
          </Button>
        </Modal.Footer>
      </Modal>

      {isOutputConfirmed && (
        <Alert variant="success">Output confirmed and saved successfully.</Alert>
      )}
    </Container>
  );
};

export default NotesMaker;